apiVersion: spec.keptn.sh/0.2.0
kind: Shipyard
metadata:
  name: "shipyard-delivery-rollout"
spec:
  stages:
  - name: prod           
    sequences:
    # Initial Deployment, Test and Evaluation
    - name: delivery        
      tasks:
      - name: deployment
        properties:
          deploymentstrategy: user_managed
      - name: test
        properties:
          teststrategy: performance
      - name: evaluation
      - name: approval
        properties:
          pass: manual
          warning: manual
    # Phase 1 of Rollout: Release, Test, Evaluate
    - name: canaryphase1
      triggeredOn:
        - event: prod.delivery.finished
          selector:
            match:
              result: "pass"
      tasks:
      - name: release
      - name: test
        properties:
          teststrategy: real-user
          canarywaitduration: 2m
      - name: evaluation
      - name: approval
        properties:
          pass: automatic
          warning: automatic
    # Phase 2 of Rollout: Release, Test, Evaluate
    - name: canaryphase2
      triggeredOn:
        - event: prod.canaryphase1.finished
          selector:
            match:
              result: "pass"
      tasks:
      - name: release
      - name: test
        properties:
          teststrategy: real-user
          canarywaitduration: 2m
      - name: evaluation
      - name: approval
        properties:
          pass: automatic
          warning: automatic
    - name: rollback
      triggeredOn:
      - event: prod.delivery.finished
        selector:
          match:
            result: "fail"
      - event: prod.canaryphase1.finished
        selector:
          match:
            result: "fail"
      - event: prod.canaryphase2.finished
        selector:
          match:
            result: "fail"
      tasks:
      - name: rollback          